remit.kafka.brokers: localhost:9093
spring:
  sleuth:
    scheduled:
      enabled: true

  application:
    name: tracingdemo
  cloud:
    stream:
      function:
        definition: someConsumer
      bindings:
        someConsumer-in-0:
          destination: tests.topic1
      kafka:
        binder:
          brokers: ${remit.kafka.brokers}

server:
  port: 8081